name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test toolchains
        run: cd integration_tests/toolchains && ./test.sh
      - name: Test rules
        run: cd integration_tests/rules && ./test.sh