name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test toolchains
        run: cd integration_tests/toolchains && ./test_linux.sh
  build_macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test toolchains
        run: cd integration_tests/toolchains && ./test_linux.sh