name: Build LLVM toolchain
on:
    workflow_dispatch:
        inputs:
            llvm_tag:
                required: true


jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt update && apt install -yqq python3 git ninja-build cmake zstd
      - name: Install ARM toolchain
        run: apt install -yqq gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi
      - name: Install AArch64 toolchain
        run: apt install -yqq gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
      - name: Install RISC-V toolchain
        run: apt install -yqq gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "llvm/llvm-project"
          ref: ${{ inputs.llvm_tag }}
      - name: Build and install
        env:
          CXXFLAGS: -w
          CFLAGS: -w
        run: |
          mkdir build && cd build
          export RT_TARGETS="x86_64-unknown-linux-gnu;arm-unknown-linux-gnueabi;aarch64-unknown-linux-gnu;riscv64-unknown-linux-gnu"
          export TOOLS="dsymutil;llvm-ar;llvm-cxxfilt;llvm-cov;llvm-dwarfdump;llvm-dpw;llvm-nm;llvm-objdump;llvm-objcopy;llvm-profdata;llvm-ranlib;llvm-readobj;llvm-strip;llvm-size;llvm-symbolizer"
          export COMPONENTS="clang;clang-format;clang-tidy;clang-resource-headers;bolt;builtins;runtimes;lld;pstl"
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;RISC-V;NVPTX;AMDGPU" \
            -DLLVM_BUILTIN_TARGETS="$RT_TARGETS" \
            -DLLVM_RUNTIME_TARGETS="$RT_TARGETS" \
            -DLLVM_LINK_LLVM_DYLIB=OFF -DLLVM_ENABLE_LTO=OFF -DLLVM_ENABLE_RUNTIMES=all \
            -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;lld;openmp;pstl" \
            -DLLVM_STATIC_LINK_CXX_STDLIB=ON -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
            -DCMAKE_INSTALL_PREFIX=$PWD/install/${{ inputs.llvm_tag }}-linux-x86_64 \
            -DCLANG_BOLT_INSTRUMENT=ON -DCMAKE_EXE_LINKER_FLAGS="-Wl,--emit-relocs,-znow" \
            -DLIBCXX_HERMETIC_STATIC_LIBRARY=ON \
            -DLLVM_TOOLCHAIN_TOOLS="$TOOLS" -DLLVM_DISTRIBUTION_COMPONENTS="$COMPONENTS;$TOOLS" \
            ../llvm

          ninja clang-bolt
          ninja install

          cd install

          for file in ${{ inputs.llvm_tag }}-linux-x86_64/bin/*; do
              if [ -f "$file" ]; then
              echo "Strip $file"
              strip $file || echo "Failed to strip"
              fi
          done

          tar --zstd -cf ${{ inputs.llvm_tag }}-linux-x86_64.tar.zst ${{ inputs.llvm_tag }}-linux-x86_64
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/install/${{ inputs.llvm_tag }}-linux-x86_64.tar.zst
          name: linux-x86_64-toolchain

  publish_release:
      needs: ["build_linux_x64"]
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3
        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            token: ${{ secrets.RELEASE_TOKEN }}
            tag_name: ${{ inputs.llvm_tag }}-${{ github.sha }}
            name: LLVM Toolchain ${{ inputs.llvm_tag }}
            prerelease: true
            files: |
              linux-x86_64-toolchain/${{ inputs.llvm_tag }}-linux-x86_64.tar.zst


